# Generated by Django 4.2.5 on 2023-10-14 10:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تماس')),
                ('text', models.TextField(verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'تماس های کاربران',
                'verbose_name_plural': 'تماس های کاربران',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_url', models.URLField(blank=True, help_text='https://...', null=True, verbose_name='لینک سایت')),
                ('site_logo', models.ImageField(upload_to='images/logos/', verbose_name='لوگوی سایت')),
                ('about', tinymce.models.HTMLField(verbose_name='درباره سایت')),
                ('owner', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی صاحب سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شبکه')),
                ('url', models.URLField(help_text='https://...', verbose_name='لینک شبکه')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='setting_app.setting', verbose_name='تنظیمات')),
            ],
            options={
                'verbose_name': 'شبکه های اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/aboutus/', verbose_name='تصویر')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutus', to='setting_app.setting', verbose_name='تنظیمات')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
