# Generated by Django 4.2.5 on 2023-10-14 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 10, 55, 58, 593748, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ارسال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده / نشده'),
        ),
    ]
