# Generated by Django 4.2.5 on 2023-10-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_app', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='حداکثر 160 کاراکتر', max_length=160, verbose_name='توضیحات کوتاه')),
                ('keywords', models.TextField(verbose_name='کلمات کلیدی')),
                ('refresh', models.CharField(blank=True, default=None, help_text='e.g: 2;url=http://example.com', max_length=200, null=True, verbose_name='ریدایرکت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seos', to='product_app.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سئو',
                'verbose_name_plural': 'سئوی محصولات',
            },
        ),
    ]
