# Generated by Django 4.2.5 on 2023-09-30 08:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: دسته بندی', max_length=100, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(help_text='مثال: category-slug', verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: برچسب', max_length=100, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(help_text='مثال: tag-slug', verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(help_text='product-name', verbose_name='اسلاگ')),
                ('content', tinymce.models.HTMLField(verbose_name='توضیحات محصول')),
                ('image', models.ImageField(upload_to='images/products/', verbose_name='تصویر محصول')),
                ('price', models.BigIntegerField(verbose_name='قیمت محصول')),
                ('delivery_time', models.IntegerField(default=0, help_text='مثال: 9 --> 9 روز کاری ', verbose_name='مدت زمان تحویل')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد موجود در انبار')),
                ('status', models.CharField(choices=[('avalible', 'موجود'), ('unavalible', 'ناموجود')], default='avalible', max_length=100, verbose_name='وضعیت')),
                ('visit_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.category', verbose_name='دسته بندی')),
                ('tags', models.ManyToManyField(to='product_app.tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='images/galleries/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='product_app.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='نظر')),
                ('answre', models.TextField(verbose_name='جواب')),
                ('date_send', models.DateField(verbose_name='تاریخ ارسال')),
                ('status', models.CharField(choices=[('accept', 'تایید شده'), ('reject', 'رد شده')], default='reject', max_length=50, verbose_name='وضعیت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_app.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-date_send'],
            },
        ),
    ]
