# Generated by Django 4.2.5 on 2023-09-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': "'تصویر'", 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pendding', 'در انتظار مشاهده'), ('accept', 'تایید شده'), ('reject', 'رد شده')], default='pendding', max_length=50, verbose_name='وضعیت'),
        ),
    ]
