# Generated by Django 4.2.5 on 2023-10-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_product_slug'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default=1, max_length=100, verbose_name='قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_app.product', verbose_name='محصول'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
