# Generated by Django 4.2.5 on 2023-10-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_count_order_price_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
