# Generated by Django 4.2.5 on 2023-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_remove_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_price',
            field=models.CharField(default=1, editable=False, max_length=100, verbose_name='قیمت کل'),
            preserve_default=False,
        ),
    ]
