# Generated by Django 4.2.5 on 2023-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0006_remove_order_product_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
