# Generated by Django 4.2.5 on 2023-10-10 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0003_alter_product_slug'),
        ('order_app', '0008_order_count_order_product_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('pay', models.CharField(max_length=100, verbose_name='پرداختی')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('status', models.BooleanField(verbose_name='پرداخت شده / نشده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.order', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_pay', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارشات موفق',
                'verbose_name_plural': 'سفارشات موفق',
            },
        ),
    ]
