# Generated by Django 4.2.5 on 2023-10-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_paidorder_address_paidorder_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidorder',
            name='count',
        ),
        migrations.AddField(
            model_name='paidorder',
            name='countf',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
