# Generated by Django 4.2.5 on 2023-10-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_remove_paidorder_count_paidorder_countf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidorder',
            old_name='pay',
            new_name='payf',
        ),
    ]
