# Generated by Django 4.2.5 on 2023-10-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0013_rename_payf_paidorder_payfull'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidorder',
            old_name='payfull',
            new_name='payment',
        ),
    ]
