# Generated by Django 4.2.5 on 2023-10-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_rename_payfull_paidorder_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidorder',
            old_name='payment',
            new_name='peyment',
        ),
    ]
