# Generated by Django 4.2.5 on 2023-10-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0015_rename_payment_paidorder_peyment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidorder',
            old_name='countf',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='paidorder',
            old_name='peyment',
            new_name='payment',
        ),
    ]
