# Generated by Django 4.2.5 on 2023-10-03 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='09147509730', help_text='09123456789', max_length=11, validators=[django.core.validators.MaxLengthValidator(11, 'شماره نباید بیشتر از 11 حرف باشه'), django.core.validators.MinLengthValidator(11, 'شماره نباید کمتر از 11 حرف باشد'), django.core.validators.RegexValidator('^(\\+98|0)?9\\d{9}$')], verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
    ]
