# Generated by Django 4.2.5 on 2023-10-04 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='09123456789', max_length=11, unique=True, validators=[django.core.validators.MaxLengthValidator(11, 'شماره نباید بیشتر از 11 حرف باشه'), django.core.validators.MinLengthValidator(11, 'شماره نباید کمتر از 11 حرف باشد'), django.core.validators.RegexValidator('^(\\+98|0)?9\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
