# Generated by Django 4.2.5 on 2023-10-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True, verbose_name='توکن بازیابی رمز'),
        ),
    ]
