# Generated by Django 4.2.5 on 2023-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_customuser_reset_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='توکن بازیابی رمز'),
        ),
    ]
