# Generated by Django 4.2.5 on 2023-10-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/sliders/', verbose_name='تصویر')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرغعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
